version: "3"

services:  
    db:
        container_name: postgres_container
        build:
            context: ./
            dockerfile: ./docker/db/Dockerfile
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db 
        volumes:
            - ./pgdata:/var/lib/postgresql/data 
            - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql  
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s 
        networks:
            - postgres
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 8G
    rabbitmq3:
        container_name: "rabbitmq"
        build:
            context: ./docker/rabbitmq 
        ports: 
            - '5672:5672' 
            - '15672:15672'
        networks:
            - postgres 
networks:
    postgres:
        driver: bridge 
volumes: 
    pgdata:  
