FROM postgres:13.3
   
COPY ./*.txt /dbExtensionBuild/ 
COPY / /dbExtensionBuild/rabbitmqfdw/ 
RUN apt-get update  

RUN apt-get -y install python3 postgresql-plpython3-13 python3-pip
#for installing multicorn
RUN apt-get -y install unzip vim
RUN apt-get -y install make gcc
RUN apt-get -y install postgresql-server-dev-13

#INSTALL multicorn
RUN mkdir /dbExtensionBuild/multicorn
ADD https://github.com/Segfault-Inc/Multicorn/archive/refs/heads/master.zip /dbExtensionBuild/multicorn
WORKDIR /dbExtensionBuild/multicorn
RUN unzip master.zip 
WORKDIR /dbExtensionBuild/multicorn/Multicorn-master/

RUN make &&  make install
 
#Other dependencies for plpython
RUN pip3 install -r /dbExtensionBuild/plpython_requirements.txt

WORKDIR /dbExtensionBuild/rabbitmqfdw/
RUN python3 setup.py install